<form class="form-signin" action="login.php" method="post">
  <h2>Please sign in</h2> 
  <label for="inputEmail" class="sr-only">Email address</label>
  <input type="email" id="inputEmail" name="username" class="form-control" placeholder="Email address" required autofocus>
  <label for="inputPassword" class="sr-only">Password</label>
  <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
  <button class="btn btn-lg btn-primary btn-block" type="submit" id="loginButton" name="login" value="Login">Sign in</button>
</form>
<center>or <a href="index.php?register=yes">Register</a></center>
